export const site = {
  name: "Anuj Karn",
  role: "Lead Full Stack Engineer",
  company: "PivotX Advisors",
  location: "New Delhi",
  coordinates: "28.6139° N, 77.2090° E",
  // The CV reads "hello@anukarn.dev" (no j) — using the site's own domain until you confirm which is real.
  email: "hello@anujkarn.dev",
  github: "https://github.com/anujkarn002",
  linkedin: "https://linkedin.com/in/anujkarn002",
  resume: "/resume/Anuj_Karn_Resume.pdf",
  summary:
    "Six-plus years across React Native, React/TypeScript, and Python/Go/Node backends — now building agentic AI and data platforms on Databricks, GCP and Azure.",
  experience: [
    {
      role: "Lead Full Stack Engineer",
      company: "PivotX Advisors",
      where: "New Delhi, India",
      from: "Apr 2025",
      to: "Present",
      current: true,
      note: "Architecture, AI engineering and delivery for an agentic data platform on Databricks and GCP; SSO and Unity Catalog access control; ISO 27001 / SOC 2-aligned lifecycle; leading engineers across front end, backend and data.",
    },
    {
      role: "Senior Software Engineer (Contract)",
      company: "Upstem Technologies",
      where: "Sydney, Australia · Remote",
      from: "Aug 2023",
      to: "Dec 2025",
      current: false,
      note: "Architected a sports social app in React Native and led five mobile developers; white-label platform serving multiple brands from one codebase; Stripe, Fastlane and GitHub Actions CI/CD.",
    },
    {
      role: "Software Engineer",
      company: "Leapfrog Technology",
      where: "Kathmandu, Nepal",
      from: "Sep 2021",
      to: "Aug 2023",
      current: false,
      note: "Offline-first inventory tracking in React Native and Go; a HIPAA-compliant booking app for a US healthcare provider; Mapbox integration for last-mile logistics.",
    },
    {
      role: "Software Engineer",
      company: "Sunya Health Solutions",
      where: "Kathmandu, Nepal",
      from: "Nov 2019",
      to: "Sep 2021",
      current: false,
      note: "OpenCV bridged into React Native over JSI for on-device diagnostics; an offline sync engine for rural health screening; regional wallet and subscription payments.",
    },
  ],
  education: { school: "University of London", degree: "B.Sc. (Hons) Computer Science, Data Science", years: "2020 — 2025" },
  stack: {
    languages: ["Python", "Go", "TypeScript", "Kotlin"],
    platforms: ["React Native", "React", "Next.js", "FastAPI", "Django"],
    infra: ["Databricks", "GCP", "Azure", "AWS", "Terraform"],
  },
};
